name: "Upload Fargate Containers"
description: "Packages and uploads, replaces reference in (eg) template.yaml"
inputs:

  role-to-assume-arn:
    description: "The secret with the ARN of the role to assume (required) eg secrets.ROLE_TO_ASSUME_ARN"
    required: true
  container-sign-kms-key-arn:
    description: "The secret with the ARN of the key to sign container images"
    required: true
  template-file:
    description: "The name of the CF template for the first application. This defaults to template.yaml"
    required: false
    default: template.yaml
  working-directory:
    description: "The working directory containing the first Fargate app (required)"
    required: true
  working-directory-1:
    description: "The working directory containing the first Fargate app (required)"
    required: true
  artifact-bucket-name-1:
    description: "The secret with the name of the first artifact S3 bucket (required) eg secrets.ARTIFACT_BUCKET_NAME_1"
    required: true
  ecr-repo-name-1:
    description: "The secret with the name of the first ECR Repo (required)  eg secrets.ecr_repo_NAME_1"
    required: true
  working-directory-2:
    description: "The working directory containing the second Fargate app"
    required: false
    default: none
  artifact-bucket-name-2:
    description: "The key of the secret with the name of the second artifact S3 bucket"
    required: false
    default: none
  ecr-repo-2:
    description: "The key of the secret with the name of the second ECR Repo"
    required: false
    default: none
  working-directory-3:
    description: "The working directory containing the third Fargate app"
    required: false
    default: none
  artifact-bucket-name-3:
    description: "The key of the secret with the name of the third artifact S3 bucket"
    required: false
    default: none
  ecr-repo-3:
    description: "The key of the secret with the name of the third ECR Repo"
    required: false
    default: none

runs:
  using: "composite"

  steps:
    - name: Change to working directory
      run: cd ${{ inputs.main-working-directory }}
      shell: bash

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Set up AWS creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume-arn }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install Cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: 'v1.9.0'

    - name: Upload Fargates to S3
      env:
        CONTAINER_SIGN_KMS_KEY_ARN: ${{ inputs.container-sign-kms-key-arn }}
        TEMPLATE_FILE: ${{ inputs.template-file }}
        GITHUB_SHA: ${{ github.sha }}
        WORKING_DIRECTORY_1: ${{ inputs.working-directory-1 }}
        ARTIFACT_BUCKET_NAME_1: ${{ inputs.artifact-bucket-name-1 }}
        ECR_REPO_NAME_1: ${{ inputs.ecr-repo-name-1 }}
        WORKING_DIRECTORY_2: ${{ inputs.working-directory-2 }}
        ARTIFACT_BUCKET_NAME_2: ${{ inputs.artifact-bucket-name-2 }}
        ECR_REPO_NAME_2: ${{ inputs.ecr-repo-name-2 }}
        WORKING_DIRECTORY_3: ${{ inputs.working-directory-3 }}
        ARTIFACT_BUCKET_NAME_3: ${{ inputs.artifact-bucket-name-3 }}
        ECR_REPO_NAME_3: ${{ inputs.ecr-repo-name-3 }}

      run: ${{ github.action_path }}/scripts/build-tag-push-ecr.sh
      shell: bash